set(ASAN OFF)
set(UBSAN OFF)
set(DIST ON)

set(NONET ON)
set(NOSOUND ON)
set(DEFAULT_PER_PIXEL_LIGHTING false)

set(PREFILL_PLAYER_NAME ON)

set(DEVILUTIONX_SYSTEM_BZIP2 OFF)
set(DEVILUTIONX_SYSTEM_LIBFMT OFF)
set(DEVILUTIONX_SYSTEM_ZLIB OFF)
set(DEVILUTIONX_STATIC_ZLIB ON)
set(DEVILUTIONX_SYSTEM_SDL2 OFF)
set(DEVILUTIONX_STATIC_SDL2 ON)
set(DEVILUTIONX_SYSTEM_SDL_IMAGE OFF)
set(DEVILUTIONX_SYSTEM_LIBPNG OFF)
set(DEVILUTIONX_DISPLAY_PIXELFORMAT SDL_PIXELFORMAT_INDEX8)

set(DEVILUTIONX_PLATFORM_FILE_UTIL_LINK_LIBRARIES "")

list(APPEND DEVILUTIONX_PLATFORM_COMPILE_OPTIONS $<$<CONFIG:Debug>:-gstabs>)

add_compile_definitions(
  SDL_DISABLE_IMMINTRIN_H
  SDL_DISABLE_XMMINTRIN_H
  SDL_DISABLE_EMMINTRIN_H
  SDL_DISABLE_PMMINTRIN_H
  SDL_DISABLE_MMINTRIN_H
)
